/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[..path]': RouteRecordInfo<'/[..path]', '/:ath(.*)', { ath: ParamValue<true> }, { ath: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/disclaimer': RouteRecordInfo<'/disclaimer', '/disclaimer', Record<never, never>, Record<never, never>>,
    '/faq': RouteRecordInfo<'/faq', '/faq', Record<never, never>, Record<never, never>>,
    '/form': RouteRecordInfo<'/form', '/form', Record<never, never>, Record<never, never>>,
    '/process': RouteRecordInfo<'/process', '/process', Record<never, never>, Record<never, never>>,
    '/support': RouteRecordInfo<'/support', '/support', Record<never, never>, Record<never, never>>,
  }
}
